# Main Configs 
title: A Pathway to Bermuda Status
description: > # "Pathway, Bermuda, Status"
url: http://pathway-to-bda-status.github.io
port: 8009

# Author Configs 
author: MariaCoding
authorweb: http://mariacoding.com/
authoremail: pathways@mariacoding.com

# Build settings
markdown: kramdown
permalink: /:categories/:title/

colors:  #in hex code if not noted else
  primary: "#D84A68" #"#F70031" 
  primary_rgb: "216, 74, 104" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  

# Pages' navigation
navigation:
  home:
    name: Home
    path: /

  about:
    name: Events
    path: /events/

  testimonies:
    name: Testimonies
    path: /testimonies/

  news:
    name: News
    path: /news/  

  info:
    name: Info
    path: /info/  

  contacts:
    name: Contacts
    path: /contacts/ 


# Contact info 
contact:
    facebookpage: https://www.facebook.com/groups/1503994363242740


# Map
map:
    zoom: 16
    address: 105 Front St, Hamilton, Bermuda
    address_details: /img/cabinet.jpg


# Footer
copyright: 2016 all rights reserved to <a href="/">We Support a Pathway to Bermuda Status</a>


#   3rd Party Settings    #

social:
  - title: facebook
    url: https://www.facebook.com/groups/1503994363242740
  - title: youtube
    url: https://youtu.be/XTNo_4DVdKA

# Jekyll & Plugins 

# Settings for analytics       
analytics :
  provider : google # Set 'provider' to the analytics provider you want to use. Set 'provider' to false to turn analytics off globally.
  google : 
      tracking_id : 'UA-75130114-1'
  getclicky :
    site_id :